apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pingdomchecks.monitoring.adrianriobo.com
spec:
  group: monitoring.adrianriobo.com
  names:
    kind: PingdomCheck
    listKind: PingdomCheckList
    plural: pingdomchecks
    singular: pingdomcheck
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PingdomCheck is the Schema for the pingdomchecks API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PingdomCheckSpec defines the desired state of PingdomCheck
          properties:
            name:
              type: string
            url:
              pattern: ^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)$
              type: string
          required:
          - name
          - url
          type: object
        status:
          description: PingdomCheckStatus defines the observed state of PingdomCheck
          properties:
            id:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: integer
          required:
          - id
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
